
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  DOMAIN_ADAPTATION_ON: False
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 16
DATASETS:
  TRAIN: ("label0_SeaShips_SMD_voc",)

  TEST: ("test1283_SeaShips_SMD_voc",)
SOLVER:
  BASE_LR: 0.004
  WEIGHT_DECAY: 0.0001
  STEPS: (12500, )
  MAX_ITER: 17500
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 2
# OUTPUT_DIR: 
#   OUTPUT_DIR: "logFRCNN0"